export const defaultVacancies = [
  {
    id: "resident-doctor-emergency",
    title: "Resident Doctor - Emergency",
    department: "Emergency",
    type: "Full time",
    experience: "1+ year",
    openings: 2,
    location: "Abhayapuri, Bongaigaon",
    description:
      "Support emergency triage, OPD review, ward rounds, case notes, and coordination with specialist doctors.",
    requirements: "MBBS registration, emergency duty readiness, clear patient communication.",
    status: "open",
  },
  {
    id: "staff-nurse-ward",
    title: "Staff Nurse - Ward & OPD",
    department: "Nursing",
    type: "Rotational shift",
    experience: "0-2 years",
    openings: 4,
    location: "Abhayapuri, Bongaigaon",
    description:
      "Manage patient monitoring, medicine timing, dressing support, documentation, and family guidance.",
    requirements: "GNM/B.Sc Nursing, valid registration preferred, calm bedside manner.",
    status: "open",
  },
  {
    id: "radiology-technician",
    title: "Radiology Technician",
    department: "Diagnostic Lab",
    type: "Full time",
    experience: "1-3 years",
    openings: 1,
    location: "Abhayapuri, Bongaigaon",
    description:
      "Handle X-ray workflow, patient positioning, equipment care, report coordination, and safety protocols.",
    requirements: "Radiology diploma, X-ray machine handling experience, radiation safety knowledge.",
    status: "open",
  },
  {
    id: "reception-executive",
    title: "Reception Executive",
    department: "Front Desk",
    type: "Full time",
    experience: "0-2 years",
    openings: 2,
    location: "Abhayapuri, Bongaigaon",
    description:
      "Manage appointments, calls, patient routing, doctor schedules, billing direction, and visitor support.",
    requirements: "Computer basics, polite communication, Assamese/Hindi/English preferred.",
    status: "open",
  },
];

export const defaultStaffMembers = [
  {
    id: "dr-ahmed",
    name: "Dr. Ahmed",
    role: "Cardiology Specialist",
    department: "Cardiology",
    status: "active",
    phone: "",
    email: "",
    member_type: "doctor",
    duty_days: ["1", "3", "5"],
    photo_url: "/lucid-origin_generate_an_image_of_male_doctor-0.jpg",
  },
  {
    id: "dr-fatima",
    name: "Dr. Fatima",
    role: "Pediatrician",
    department: "Pediatrics",
    status: "active",
    phone: "",
    email: "",
    member_type: "doctor",
    duty_days: ["1", "2", "3", "4", "5", "6"],
    photo_url: "/lucid-origin_generate_an_image_of_female_doctor_who_is_wearing_hijab_also-0.jpg",
  },
  {
    id: "radiology-team",
    name: "Radiology Team",
    role: "Diagnostic Support",
    department: "Diagnostic Lab",
    status: "active",
    phone: "",
    email: "",
    member_type: "staff",
    duty_days: ["1", "2", "3", "4", "5", "6"],
    photo_url: "",
  },
];

export const defaultDoctors = [
  {
    id: "dr-ahmed",
    name: "Dr. Ahmed",
    photo_url: "/lucid-origin_generate_an_image_of_male_doctor-0.jpg",
    department: "Cardiology",
    specialization: "Cardiology (Heart)",
    qualification: "MBBS, MD",
    experience: "8 years",
    consultation_fee: 500,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "204",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["monday", "wednesday", "friday"],
      shift_start: "10:00",
      shift_end: "14:00",
    },
  },
  {
    id: "dr-fatima",
    name: "Dr. Fatima",
    photo_url: "https://img.freepik.com/premium-photo/close-up-muslim-female-doctor-protective-mask-looking-front-working-hospital_249974-5147.jpg",
    department: "Pediatrics",
    specialization: "Pediatrics (Child)",
    qualification: "MBBS, DCH",
    experience: "6 years",
    consultation_fee: 400,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "102",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
      shift_start: "09:30",
      shift_end: "13:30",
    },
  },
  {
    id: "dr-robert",
    name: "Dr. Robert",
    photo_url: "/lucid-origin_generate_an_image_of_nurologist_specialist_doctor-0.jpg",
    department: "Neurology",
    specialization: "Neurology (Brain)",
    qualification: "MBBS, DM",
    experience: "9 years",
    consultation_fee: 550,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "303",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      shift_start: "11:00",
      shift_end: "15:00",
    },
  },
  {
    id: "dr-verma",
    name: "Dr. Verma",
    photo_url: "/lucid-origin_generate_an_image_of_cancer_specialist_doctor-0.jpg",
    department: "Oncology",
    specialization: "Oncology (Cancer)",
    qualification: "MBBS, MD",
    experience: "10 years",
    consultation_fee: 600,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "410",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["monday", "wednesday", "friday"],
      shift_start: "10:30",
      shift_end: "14:30",
    },
  },
  {
    id: "dr-khan-dentistry",
    name: "Dr. Khan",
    photo_url: "/lucid-origin_generate_an_image_of_male_dentist_doctor-0.jpg",
    department: "Dentistry",
    specialization: "Dentistry (Teeth)",
    qualification: "BDS",
    experience: "7 years",
    consultation_fee: 350,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "110",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"],
      shift_start: "10:00",
      shift_end: "16:00",
    },
  },
  {
    id: "dr-ray",
    name: "Dr. Ray",
    photo_url: "/blank-profile-picture-973460_960_720.webp",
    department: "Dermatology",
    specialization: "Dermatology (Hair & Skin)",
    qualification: "MBBS, DVD",
    experience: "5 years",
    consultation_fee: 400,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "115",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["tuesday", "thursday", "saturday"],
      shift_start: "12:00",
      shift_end: "16:00",
    },
  },
  {
    id: "dr-parbin",
    name: "Dr. Parbin",
    photo_url: "/lucid-origin_generate_an_image_of_female_doctor_who_is_wearing_hijab_also-0.jpg",
    department: "Endocrinology",
    specialization: "Endocrinology (Diabetes)",
    qualification: "MBBS, MD",
    experience: "6 years",
    consultation_fee: 450,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "305",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["monday", "wednesday", "friday"],
      shift_start: "09:00",
      shift_end: "13:00",
    },
  },
  {
    id: "dr-baruah",
    name: "Dr. Baruah",
    photo_url: "/blank-profile-picture-973460_960_720.webp",
    department: "Surgery",
    specialization: "General Surgery",
    qualification: "MBBS, MS",
    experience: "11 years",
    consultation_fee: 650,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "501",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["tuesday", "thursday", "saturday"],
      shift_start: "11:00",
      shift_end: "15:00",
    },
  },
  {
    id: "dr-priya",
    name: "Dr. Priya",
    photo_url: "/ChatGPT Image May 20, 2026, 08_32_27 AM.png",
    department: "Gastroenterology",
    specialization: "Gastroenterologist",
    qualification: "MBBS, MD",
    experience: "7 years",
    consultation_fee: 480,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "210",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["monday", "tuesday", "wednesday", "thursday", "friday"],
      shift_start: "10:00",
      shift_end: "14:00",
    },
  },
  {
    id: "dr-devi",
    name: "Dr. Devi",
    photo_url: "/ChatGPT Image May 20, 2026, 08_37_20 AM.png",
    department: "Gynecology",
    specialization: "Gynecologist",
    qualification: "MBBS, DGO",
    experience: "9 years",
    consultation_fee: 520,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "220",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["monday", "wednesday", "friday"],
      shift_start: "09:00",
      shift_end: "13:00",
    },
  },
  {
    id: "dr-barman",
    name: "Dr. Barman",
    photo_url: "/ChatGPT Image May 20, 2026, 08_39_58 AM.png",
    department: "Ophthalmology",
    specialization: "Ophthalmologist",
    qualification: "MBBS, MS",
    experience: "8 years",
    consultation_fee: 530,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "230",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["tuesday", "thursday", "saturday"],
      shift_start: "11:00",
      shift_end: "15:00",
    },
  },
  {
    id: "dr-choudhury",
    name: "Dr. Choudhury",
    photo_url: "/ChatGPT Image May 20, 2026, 08_42_20 AM.png",
    department: "ENT",
    specialization: "ENT Specialist",
    qualification: "MBBS, DLO",
    experience: "7 years",
    consultation_fee: 450,
    languages_known: ["Assamese", "Hindi", "English"],
    room_number: "240",
    status: "active",
    availability_override: "auto",
    roster: {
      duty_days: ["monday", "wednesday", "friday"],
      shift_start: "10:00",
      shift_end: "14:00",
    },
  },
];
